name: Gradle Check

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os: [ ubuntu-latest, macOS-latest ]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_VENDOR }}
          java-version: ${{ vars.GRADLE_JAVA_VERSION }}
          java-package: jre
          cache: 'gradle'
      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties

      - uses: actions/setup-java@v4
        with:
          distribution: ${{ vars.JAVA_VENDOR }}
          java-version: ${{ vars.JAVA_VERSION }}
          check-latest: true
      - run: printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties
      - run: java --version

      - name: Generate Source
        run: ./genSrc.sh --log="INFO" --tabLength=2 --sourceDirectory="programs/src/main/java" --rpc="${{ secrets.RPC_URL }}" --baseDelayMillis=200 --numThreads=5
        env:
          GITHUB_ACTOR: ${{ secrets.GPR_USER }}
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Gradle Check
        run: ./gradlew -Pgpr.sava.user=${{ secrets.GPR_USER }} -Pgpr.sava.token=${{ secrets.GPR_TOKEN }} -PtargetJava=${{ vars.JAVA_VERSION }} check --stacktrace --no-daemon
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}