name: Publish Release

on:
  create:
    tags:
      - '\d+\.\d+\.\d+'

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
          java-package: jre
          cache: 'gradle'
      - run: printf "org.gradle.java.home=%s" "$JAVA_HOME" > gradle.properties

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 22
          check-latest: true
      - run: printf "\norg.gradle.java.installations.paths=%s" "$JAVA_HOME" >> gradle.properties
      - run: java --version

      - name: Generate Source
        run: ./genSrc.sh --log="INFO" --tabLength=2 --sourceDirectory="programs/src/main/java" --rpc="${{ secrets.RPC_URL }}" --baseDelayMillis=200 --numThreads=5
        env:
          GITHUB_ACTOR: ${{ secrets.GPR_USER }}
          GITHUB_TOKEN: ${{ secrets.GPR_TOKEN }}

      - name: Gradle Check
        run: ./gradlew -Pgpr.sava.user=${{ secrets.GPR_USER }} -Pgpr.sava.token=${{ secrets.GPR_TOKEN }} -PtargetJava=22 check --stacktrace --no-daemon
        env:
          GITHUB_ACTOR: ${{ secrets.GITHUB_ACTOR }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Github Packages
        run: ./gradlew -Pgpr.sava.user=${{ secrets.GPR_USER }} -Pgpr.sava.token=${{ secrets.GPR_TOKEN }} -PtargetJava=22 :anchor-programs:publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
